[package]
name = "httpie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
reqwest = "0.11.22"
colored = "2.0.4"
anyhow = "1.0.75"
jsonxf = "1.1.1"
mime = "0.3.17"
tokio = "1.33.0"
